"""Consigne envoyee au modele de vision, page par page.

C'est la piece qui bouge le plus : chaque regle ajoutee ici evite un
post-traitement en aval. Elle vit seule pour qu'on la relise sans avoir
a traverser le code d'appel."""
from __future__ import annotations


VISION_PROMPT = (
    "Convertis integralement cette page en Markdown.\n"
    "\n"
    "Contenu textuel :\n"
    "- Preserve la hierarchie des titres et sous-titres.\n"
    "- Respecte l'ordre logique de lecture : sur une mise en page en "
    "colonnes, suis le fil du texte, ne lis pas en travers des colonnes.\n"
    "- Preserve les listes (a puces et numerotees), le gras, l'italique et "
    "le code inline.\n"
    "- Rends les tableaux en HTML, et jamais en syntaxe pipe : <table>, "
    "<tr>, <th> pour les cellules d'en-tete, <td> pour les autres. Une "
    "cellule qui s'etend sur plusieurs colonnes ou plusieurs lignes porte "
    "colspan ou rowspan. C'est precisement ce que Markdown ne sait pas "
    "dire : une double entree ou une cellule fusionnee se rend donc en "
    "tableau, elle ne se defait pas en texte.\n"
    "- Le contenu d'une cellule reste du HTML : <b>, <i>, et <ul><li> pour "
    "une liste a puces. Pas de ** ni de tirets de puce dans un <td>.\n"
    "- Une liste a plusieurs niveaux garde ses niveaux : la sous-liste "
    "s'ouvre DANS le <li> qui la porte, en <li>texte<ul><li>...</li></ul></li>, "
    "et jamais a la suite comme si tous les points etaient de meme rang. "
    "Un changement de puce, de retrait ou de taille signale un niveau : "
    "un tiret puis des carres, ou une puce ronde puis un tiret. Cela vaut "
    "dans le texte courant comme dans une cellule de tableau.\n"
    "- Presente chaque tableau en HTML indente : une balise de structure par "
    "ligne (<table>, <thead>, <tbody>, <tr>), decalee de quatre espaces par "
    "niveau. Une cellule <td> ou <th> tient sur sa propre ligne. Les listes "
    "a puces dans une cellule suivent la meme regle : <ul> sur sa ligne, "
    "chaque <li> sur la sienne, indentes sous leur cellule.\n"
    "- N'emploie <table> que pour un vrai tableau : hors tableau, toute la "
    "page reste du Markdown.\n"
    "- Si la page commence par la SUITE d'un tableau ouvert a la page "
    "precedente, rends ces lignes en <tr> dans un <table>. Ne transforme "
    "jamais un en-tete de colonnes en titre Markdown (##), et n'invente pas "
    "d'en-tete : les fragments seront recolles ensuite.\n"
    "- Une cellule n'est jamais un titre. Meme isolee en haut de page, meme "
    "en gras ou plus grande que le reste, la premiere cellule d'une ligne "
    "reste une cellule : rends la ligne entiere, avec toutes ses colonnes, "
    "vides comprises. Un tableau garde le meme nombre de colonnes du debut "
    "a la fin.\n"
    "- Une cellule peut contenir plusieurs phrases, plusieurs paragraphes ou "
    "une liste : tout cela reste dans le MEME <td>. Ne cree pas un <tr> par "
    "paragraphe, sinon les cellules des autres colonnes se retrouvent vides "
    "et le tableau ne veut plus rien dire. Un <tr> correspond a une ligne du "
    "tableau imprime, delimitee par ses filets horizontaux.\n"
    "- Prends en compte les notes de bas de page, les encadres et les "
    "citations : ce sont du contenu, pas de la mise en page.\n"
    "\n"
    "Mathematiques :\n"
    "- TOUT ce qui est mathematique s'ecrit en LaTeX, sans exception : "
    "$...$ au fil du texte, $$...$$ pour une formule posee seule sur sa "
    "ligne. Cela vaut aussi dans un titre, dans une puce et dans une cellule "
    "de tableau.\n"
    "- N'ecris jamais une expression avec des caracteres speciaux quand "
    "LaTeX sait la dire : `x²` s'ecrit $x^2$, `√2` s'ecrit $\\sqrt{2}$, "
    "`≤` s'ecrit \\leq, `≠` s'ecrit \\neq, `∈` s'ecrit \\in, `×` s'ecrit "
    "\\times, `π` s'ecrit \\pi, `ℝ` s'ecrit \\mathbb{R}, `∑` s'ecrit \\sum. "
    "Un exposant ou un indice en petits caracteres devient ^ et _.\n"
    "- Une fraction ecrite sur deux etages devient \\frac{}{} ; une racine, "
    "\\sqrt{} ; un nom de fonction, \\cos, \\sin, \\log, \\ln.\n"
    "- Sont mathematiques et passent donc en LaTeX : une equation, une "
    "inequation, une identite, une expression algebrique, une fonction et "
    "son image ($f(x) = k$), une relation entre grandeurs ($U = RI$), un "
    "intervalle, un ensemble, une coordonnee ($(x, y)$), une variable citee "
    "seule dans une phrase.\n"
    "- Ne sont PAS mathematiques et restent en texte : un numero de page, "
    "une date, un horaire, un effectif, une duree, une plage d'annees "
    "(2019-2020), une reference d'article, un pourcentage en toutes lettres, "
    "et une mesure avec son unite (12 m², 19 °C, 45 min) qui garde son "
    "ecriture courante.\n"
    "- Une ligne de code reste du code, dans un bloc ```, meme si elle porte "
    "un signe egal : `S = 0` n'est pas une formule.\n"
    "\n"
    "Figures (graphiques, diagrammes, schemas, illustrations) :\n"
    "- Pour chaque figure porteuse d'information, ajoute une description "
    "textuelle precise de ce qu'elle transmet, en citation Markdown pour la "
    "distinguer du texte du document :\n"
    "  > **Figure : <titre ou sujet>**\n"
    "  > la description, chaque ligne prefixee par le chevron\n"
    "  Cette description est la seule chose que tu rediges toi-meme : le "
    "reste doit venir du document.\n"
    "- Transcris les libelles, les valeurs, les legendes, les axes et les "
    "relations visibles (fleches, hierarchies, regroupements, evolutions).\n"
    "- Ne decris PAS les elements purement decoratifs : logos, filets, "
    "bandeaux, images d'illustration sans information.\n"
    "- N'ecris JAMAIS d'image Markdown : pas de ![...](...). Tu ne vois "
    "qu'une image de page, tu ne connais ni l'adresse ni le nom de fichier "
    "d'une illustration, et toute cible que tu ecrirais serait inventee. Une "
    "figure se rend par sa description en citation, jamais par un lien.\n"
    "\n"
    "Fidelite :\n"
    "- N'invente AUCUNE information absente de la page. Si un texte est "
    "illisible, ecris [illisible] plutot que de deviner.\n"
    "- Ne resume pas, ne reformule pas, ne commente pas.\n"
    "\n"
    "Contexte : cette page fait partie d'un document PDF multi-pages, mais "
    "le Markdown final sera CONCATENE en un seul document mono-page. En "
    "consequence, IGNORE COMPLETEMENT les elements repetitifs de mise en "
    "page qui creeraient du bruit :\n"
    "- numeros de page (ex. 'Page 3', '3/12', '- 3 -')\n"
    "- en-tetes de page recurrents (titre du document repete, nom de "
    "chapitre repete en haut de chaque page)\n"
    "- pieds de page recurrents (mentions de copyright, url du site, date "
    "de publication, nom d'auteur qui apparaissent en bas de chaque page)\n"
    "- lignes de separation decoratives (---, ***, etc. si elles ne sont "
    "que des ornements graphiques)\n"
    "\n"
    "Sortie :\n"
    "- Ne rajoute AUCUN commentaire de ta part, n'ajoute aucun texte avant "
    "ni apres le Markdown.\n"
    "- N'emballe PAS ta reponse dans un bloc de code (pas de ```markdown, "
    "pas de ```html) : le HTML des tableaux s'ecrit directement dans le "
    "Markdown, sans emballage.\n"
    "- Retourne uniquement le contenu Markdown de la page, pret a etre "
    "concatene avec les autres pages."
)
